Re-add alert confirmation before Cockpit Storage
rhinstaller/anaconda-webui pull request #369
Opened 2024-07-25 11:43 UTC by adamkankovsky

2024-07-25 12:24 UTC, KKoukiou reviewed
Please check tests. :)

2024-07-25 12:31 UTC, adamkankovsky commented
> Please check tests. :)

Sure I know about the tests, this was just a checkpoint

2024-07-31 15:39 UTC, garrett commented
Nice! It's getting there.

That isn't based on a recent mockup, however. For continence, here's the latest (which I shared in Jira somewhere also, but can't find the specific ticket):

![image](https://github.com/user-attachments/assets/0bf129de-ae5c-43c5-8646-92db8252e3da)

The good news is, it's functionally the same, but with a little bit of added text to make it clear that this should not be used in a typical installation.

Text:

> The storage editor lets you resize, delete, and create partitions. It can set up LVM and much more. It is meant to be used as an advanced utility and not intended to be used in a typical installation.
>
> **Any changes you make in the storage editor will immediately affect your devices.**

2024-08-02 13:05 UTC, KKoukiou requested changes
Some small changes needed.

2024-08-02 13:05 UTC, KKoukiou commented on src/components/storage/CockpitStorageIntegration.jsx
> +              title="Modify storage"
Please translate that. _("Modify storage")

2024-08-02 13:05 UTC, KKoukiou commented on src/components/storage/CockpitStorageIntegration.jsx
> +              aria-describedby="modal-title-icon-description"
Do you need this? You dont even have an icon. I suggest removing it.

2024-08-02 13:05 UTC, KKoukiou commented on src/components/storage/CockpitStorageIntegration.jsx
> +                <span id="modal-title-icon-description">
You can make this span wrapper a TextContent.

Then you can use strong text and such stylings by using Text variants.  https://www.patternfly.org/components/text

Then you wont need the <br> i think

2024-08-02 13:08 UTC, KKoukiou requested changes

2024-08-02 13:08 UTC, KKoukiou commented on src/components/storage/CockpitStorageIntegration.jsx
> +    const [confirmed, setConfirmed] = useState(false);
Using is as a prefix for boolean state variables is a common convention in React and JavaScript coding practices.

For consistency purpose please change this to [isConfirmed, set..]

2024-08-02 15:18 UTC, KKoukiou reviewed
Did the changes my self so that I can do release including this today.

2024-08-02 15:18 UTC, KKoukiou commented on src/components/storage/CockpitStorageIntegration.jsx
> +            <Modal
Will be nice to have it as seperate component for readability purposes.

2024-08-02 15:24 UTC, KKoukiou approved these changes

2024-08-03 07:26 UTC, merged

2024-08-05 05:09 UTC, adamkankovsky commented
Thanks for the changes and the suggestions.