Adding keyboard settings with localectl
rhinstaller/anaconda-webui pull request #561
Opened 2024-12-18 11:20 UTC by adamkankovsky

![image](https://github.com/user-attachments/assets/a2b6d6c0-82db-42f9-b197-644498360729)

2024-12-18 12:41 UTC, KKoukiou reviewed
Great job, please add tests.

2024-12-18 12:41 UTC, KKoukiou commented on src/actions/localization-actions.js
> +        try {
Please avoid using try catch here. Failures in these functions shoudl not be caught and ignored, but rather propagated to to main error handler, where they are raised as CriticalErrors and stopping the installation.

2024-12-18 12:41 UTC, KKoukiou commented on src/actions/localization-actions.js
> +            dispatch(getKeyboardLayoutsAction({ language }));
Please dont add this here. Find where getLanguageAction is called in src/apis/localization.js and do this bellow that.

2024-12-18 12:41 UTC, KKoukiou commented on src/actions/localization-actions.js
> +        } catch (error) {
No try catch, this needs to be handled as CriticalError.

2024-12-18 12:41 UTC, KKoukiou commented on src/apis/localization.js
> +    const filePath = "/usr/share/X11/xkb/rules/evdev.lst";
Parsing this file sounds like not the most robust solution. I dont object it, but maybe we could think of something more stable? 

This info could be retrieved I think from the python bindings of xdb, python-xkbcommon

So we could have a python script that generates this, converts it into a JSON file, which we can easily consume from Javascript. 

@jkonecny12 what do you think? Do we want this solution, as long as it's tested and wait for Gnome to resolve this by implementing the localed APIs for Workstation?

2024-12-18 12:41 UTC, KKoukiou commented on src/components/localization/InstallationLanguage.jsx
> +          aria-label="Select Keyboard Layout"
You dont need aria label, just add an id to the element, and supply that to fieldId of the FormGroup.

2024-12-19 13:00 UTC, jkonecny12 requested changes
We should use existing code in Anaconda. In general keyboard layouts logic is hard a lot of specifics which might give us a lot of headache especially if we would keep the code on two places.

2025-02-13 14:09 UTC, KKoukiou commented on src/components/localization/InstallationLanguage.jsx
> +            <Title headingLevel="h3">{_("Choose Language and Keyboard")}</Title>
Adam can you also please remove this? It's not in the mockups.

2025-02-13 14:44 UTC, KKoukiou commented
> The new test is expected to fail for fedora-42. Please use skipImage for fedora-42-boot, testKeyboardLayoutSelection

Or actually sorry this will break 42 actually. Let's display the keyboard selection only if the API exists?

2025-02-13 17:42 UTC, KKoukiou requested changes
Please check comments and rebase.

2025-02-18 07:05 UTC, KKoukiou approved these changes

2025-02-18 07:13 UTC, adamkankovsky reviewed
It looks very good. Thank you. 
I'm just not sure if the pr includes test/static-code

2025-02-18 08:46 UTC, KKoukiou commented
Fedora-42-boot: # testBasic (__main__.TestStorageMountPoints.testBasic)  - Unnrelated flake.

2025-02-18 09:04 UTC, merged